In [23]:
import tensorflow
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint
import os
import numpy as np

In [3]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57026/57026 [==============================] - 0s 1us/step


In [4]:
X_train.shape

(404, 13)

In [5]:
X_valid.shape

(102, 13)

In [6]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [7]:
y_train[0]

15.2

### design neural network

In [8]:
model = Sequential()

# first hidden layer
model.add(Dense(32, activation='relu', input_dim=13))
model.add(BatchNormalization())

# second hidden layer
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# output layer
model.add(Dense(1, activation='linear'))

2024-03-01 12:01:06.617085: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Max
2024-03-01 12:01:06.617126: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 96.00 GB
2024-03-01 12:01:06.617136: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 36.00 GB
2024-03-01 12:01:06.617187: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-03-01 12:01:06.617213: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 batch_normalization (Batch  (None, 32)                128       
 Normalization)                                                  
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 batch_normalization_1 (Bat  (None, 16)                64        
 chNormalization)                                                
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 1

In [10]:
model.compile(loss='mean_squared_error', optimizer='nadam')

In [13]:
output_dir = 'model_output/'

In [14]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [15]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [16]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5',
                                  save_weights_only=True)

In [18]:
model.fit(X_train, y_train, batch_size=8, epochs=32, verbose=1,
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint])

Epoch 1/32
51/51 [==============================] - 1s 16ms/step - loss: 553.1384 - val_loss: 540.1693
Epoch 2/32
51/51 [==============================] - 1s 16ms/step - loss: 530.5635 - val_loss: 531.1677
Epoch 3/32
51/51 [==============================] - 1s 16ms/step - loss: 509.0949 - val_loss: 495.7732
Epoch 4/32
51/51 [==============================] - 1s 16ms/step - loss: 480.5261 - val_loss: 457.2907
Epoch 5/32
51/51 [==============================] - 1s 17ms/step - loss: 452.2103 - val_loss: 424.5210
Epoch 6/32
51/51 [==============================] - 1s 17ms/step - loss: 416.9475 - val_loss: 406.9420
Epoch 7/32
51/51 [==============================] - 1s 17ms/step - loss: 376.4994 - val_loss: 334.1323
Epoch 8/32
51/51 [==============================] - 1s 17ms/step - loss: 336.3553 - val_loss: 312.0218
Epoch 9/32
51/51 [==============================] - 1s 16ms/step - loss: 293.1531 - val_loss: 262.2107
Epoch 10/32
51/51 [==============================] - 1s 16ms/step - loss:

### perform inference

In [19]:
model.load_weights(output_path + '/weights.31.hdf5')

In [20]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [25]:
X_valid[42].shape

(13,)

In [21]:
y_valid[42]

14.1

In [24]:
model.predict(np.reshape(X_valid[42], [1,13]))

1/1 [==============================] - 1s 580ms/step


array([[19.005325]], dtype=float32)